import cors from "cors";
import express from "express";
import { randomBytes, randomUUID, scryptSync, timingSafeEqual } from "crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "fs";
import { dirname, join } from "path";

type User = { id: string; name: string; email: string; passwordHash: string; createdAt: string };
type Member = { id: string; name: string }; type Share = { userId: string; amount: number };
type Expense = { id: string; description: string; amount: number; paidBy: string; createdAt: string; shares: Share[] };
type Settlement = { id: string; fromUserId: string; toUserId: string; amount: number; createdAt: string };
type Message = { id: string; userId: string; content: string; createdAt: string; type?: "system" | "message" };
type Group = { id: string; ownerId: string; name: string; createdAt: string; members: Member[]; expenses: Expense[]; settlements: Settlement[]; messages: Message[] };
type Store = { users: User[]; sessions: Record<string, string>; groups: Group[] };
type AuthRequest = express.Request & { user?: User };
const storePath = join(process.cwd(), "data", "splitly.json");
function load(): Store { if (!existsSync(storePath)) return { users: [], sessions: {}, groups: [] }; const raw = JSON.parse(readFileSync(storePath, "utf8")); return Array.isArray(raw) ? { users: [], sessions: {}, groups: raw } : raw; }
function save(store: Store) { mkdirSync(dirname(storePath), { recursive: true }); writeFileSync(storePath, JSON.stringify(store, null, 2)); }
function cents(value: number) { return Math.round(value * 100) / 100; }
function publicUser(user: User) { return { id: user.id, name: user.name, email: user.email }; }
function hashPassword(password: string) { const salt = randomBytes(16).toString("hex"); return `${salt}:${scryptSync(password, salt, 64).toString("hex")}`; }
function validPassword(password: string, stored: string) { const [salt, hash] = stored.split(":"); return Boolean(salt && hash) && timingSafeEqual(scryptSync(password, salt, 64), Buffer.from(hash, "hex")); }
function balances(group: Group) { const totals = new Map(group.members.map(member => [member.id, 0])); group.expenses.forEach(expense => { totals.set(expense.paidBy, cents((totals.get(expense.paidBy) || 0) + expense.amount)); expense.shares.forEach(share => totals.set(share.userId, cents((totals.get(share.userId) || 0) - share.amount))); }); group.settlements.forEach(item => { totals.set(item.fromUserId, cents((totals.get(item.fromUserId) || 0) + item.amount)); totals.set(item.toUserId, cents((totals.get(item.toUserId) || 0) - item.amount)); }); return [...totals].map(([userId, amount]) => ({ userId, amount })); }
function groupFor(store: Store, id: string | string[], userId: string, res: express.Response) { const groupId = Array.isArray(id) ? id[0] : id; const group = store.groups.find(g => g.id === groupId && g.ownerId === userId); if (!group) res.status(404).json({ error: "Group not found." }); return group; }
const app = express(); app.use(cors()); app.use(express.json());
function requireAuth(req: AuthRequest, res: express.Response, next: express.NextFunction) { const token = req.headers.authorization?.replace(/^Bearer\s+/i, ""); const store = load(), user = token && store.users.find(item => item.id === store.sessions[token]); if (!user) return res.status(401).json({ error: "Please sign in to continue." }); req.user = user; next(); }

app.post("/api/auth/signup", (req, res) => { const name = String(req.body.name || "").trim(), email = String(req.body.email || "").trim().toLowerCase(), password = String(req.body.password || ""); if (!name || !/^\S+@\S+\.\S+$/.test(email) || password.length < 6) return res.status(400).json({ error: "Enter your name, a valid email, and a password of at least 6 characters." }); const store = load(); if (store.users.some(user => user.email === email)) return res.status(409).json({ error: "An account with this email already exists." }); const user: User = { id: randomUUID(), name, email, passwordHash: hashPassword(password), createdAt: new Date().toISOString() }, token = randomBytes(32).toString("hex"); store.users.push(user); store.sessions[token] = user.id; save(store); res.status(201).json({ user: publicUser(user), token }); });
app.post("/api/auth/signin", (req, res) => { const email = String(req.body.email || "").trim().toLowerCase(), password = String(req.body.password || ""), store = load(), user = store.users.find(item => item.email === email); if (!user || !validPassword(password, user.passwordHash)) return res.status(401).json({ error: "Incorrect email or password." }); const token = randomBytes(32).toString("hex"); store.sessions[token] = user.id; save(store); res.json({ user: publicUser(user), token }); });
app.get("/api/auth/me", requireAuth, (req: AuthRequest, res) => res.json(publicUser(req.user!)));
app.post("/api/auth/signout", requireAuth, (req, res) => { const token = req.headers.authorization?.replace(/^Bearer\s+/i, ""), store = load(); if (token) delete store.sessions[token]; save(store); res.status(204).end(); });

app.get("/api/groups", requireAuth, (req: AuthRequest, res) => { const userId = req.user!.id; res.json(load().groups.filter(g => g.ownerId === userId).map(g => ({ id: g.id, name: g.name, createdAt: g.createdAt, memberCount: g.members.length, totalSpent: cents(g.expenses.reduce((sum, e) => sum + e.amount, 0)), myBalance: balances(g).find(b => b.userId === userId)?.amount || 0 }))); });
app.post("/api/groups", requireAuth, (req: AuthRequest, res) => { const name = String(req.body.name || "").trim(), names = (Array.isArray(req.body.members) ? req.body.members : []).map((x: unknown) => String(x).trim()).filter(Boolean) as string[], user = req.user!; if (!name) return res.status(400).json({ error: "A group name is required." }); const members = [{ id: user.id, name: user.name }, ...[...new Set(names.filter(item => item.toLowerCase() !== user.name.toLowerCase()))].map(memberName => ({ id: randomUUID(), name: memberName }))]; const group: Group = { id: randomUUID(), ownerId: user.id, name, createdAt: new Date().toISOString(), members, expenses: [], settlements: [], messages: [] }; const store = load(); store.groups.push(group); save(store); res.status(201).json(group); });
app.get("/api/groups/:groupId", requireAuth, (req: AuthRequest, res) => { const group = groupFor(load(), req.params.groupId, req.user!.id, res); if (group) res.json(group); });
app.post("/api/groups/:groupId/members", requireAuth, (req: AuthRequest, res) => { const store = load(), group = groupFor(store, req.params.groupId, req.user!.id, res), name = String(req.body.name || "").trim(); if (!group) return; if (!name) return res.status(400).json({ error: "A member name is required." }); const member = { id: randomUUID(), name }; group.members.push(member); save(store); res.status(201).json(member); });
app.get("/api/groups/:groupId/expenses", requireAuth, (req: AuthRequest, res) => { const group = groupFor(load(), req.params.groupId, req.user!.id, res); if (group) res.json(group.expenses); });
app.post("/api/groups/:groupId/expenses", requireAuth, (req: AuthRequest, res) => { const store = load(), group = groupFor(store, req.params.groupId, req.user!.id, res); if (!group) return; const description = String(req.body.description || "").trim(), amount = Number(req.body.amount), paidBy = String(req.body.paidBy || ""), shares = req.body.shares as Share[]; if (!description || !Number.isFinite(amount) || amount <= 0 || !group.members.some(m => m.id === paidBy) || !Array.isArray(shares) || !shares.length) return res.status(400).json({ error: "Enter a description, valid amount, payer, and shares." }); if (shares.some(s => !group.members.some(m => m.id === s.userId) || !Number.isFinite(Number(s.amount)) || Number(s.amount) < 0) || Math.abs(cents(shares.reduce((sum, s) => sum + Number(s.amount), 0)) - cents(amount)) > .001) return res.status(400).json({ error: "Shares must exactly equal the expense amount." }); const expense: Expense = { id: randomUUID(), description, amount: cents(amount), paidBy, createdAt: new Date().toISOString(), shares: shares.map(s => ({ userId: s.userId, amount: cents(Number(s.amount)) })) }; group.expenses.unshift(expense); group.messages.push({ id: randomUUID(), userId: paidBy, content: `added “${description}” — ₹${expense.amount.toLocaleString("en-IN")}`, createdAt: expense.createdAt, type: "system" }); save(store); res.status(201).json(expense); });
app.get("/api/groups/:groupId/balances", requireAuth, (req: AuthRequest, res) => { const group = groupFor(load(), req.params.groupId, req.user!.id, res); if (group) res.json(balances(group)); });
app.get("/api/groups/:groupId/settlements", requireAuth, (req: AuthRequest, res) => { const group = groupFor(load(), req.params.groupId, req.user!.id, res); if (group) res.json(group.settlements); });
app.post("/api/groups/:groupId/settlements", requireAuth, (req: AuthRequest, res) => { const store = load(), group = groupFor(store, req.params.groupId, req.user!.id, res); if (!group) return; const { fromUserId, toUserId } = req.body, amount = Number(req.body.amount); if (!group.members.some(m => m.id === fromUserId) || !group.members.some(m => m.id === toUserId) || fromUserId === toUserId || !Number.isFinite(amount) || amount <= 0) return res.status(400).json({ error: "Enter a valid settlement." }); const settlement: Settlement = { id: randomUUID(), fromUserId, toUserId, amount: cents(amount), createdAt: new Date().toISOString() }; group.settlements.push(settlement); save(store); res.status(201).json(settlement); });
app.get("/api/groups/:groupId/messages", requireAuth, (req: AuthRequest, res) => { const group = groupFor(load(), req.params.groupId, req.user!.id, res); if (group) res.json(group.messages); });
app.post("/api/groups/:groupId/messages", requireAuth, (req: AuthRequest, res) => { const store = load(), group = groupFor(store, req.params.groupId, req.user!.id, res); if (!group) return; const userId = String(req.body.userId || ""), content = String(req.body.content || "").trim(); if (!group.members.some(m => m.id === userId) || !content) return res.status(400).json({ error: "Choose a sender and enter a message." }); const message: Message = { id: randomUUID(), userId, content, createdAt: new Date().toISOString(), type: "message" }; group.messages.push(message); save(store); res.status(201).json(message); });
app.listen(3001, () => console.log("Splitly API listening at http://localhost:3001"));
